### ISSUE TITLE
Controlar o uso do operador !!

### ISSUE THREAD

**Issue by rafaeltoledo** [VihDuarte/GitHubClient#2]
Principalmente nos Fragments, o uso do operador `!!` acaba por inutilizar uma das grandes vantagens do Kotlin que é o null safety. Caso haja certeza de que o valor não será nulo, tente já declarar os atributos como tal :)

**Comment by VihDuarte** [comment]
Muito obrigado pelo feedback, realizei a alteração sugerida.
