### ISSUE TITLE
Inverter o acoplamento entre Fragments

### ISSUE THREAD

**Issue by rafaeltoledo** [VihDuarte/GitHubClient#4]
A ideia dos Fragments, é que eles sejam componentes reutilizáveis. Mesmo que isso não aconteça, devido ao fluxo que temos hoje no app, eles dependem diretamente da Activity (fazendo cast). O ideal é que essa dependência seja invertida: os fragments não conheçam detalhes da Activity. Como você tem um tratamento da Toolbar para a navegação, tente deixar esse comportamento na Activity e tirar esse conhecimento dos Fragments

**Comment by VihDuarte** [comment]
Muito obrigado pelo feedback, realizei a alteração sugerida.
